---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /ci
  path: major-tom

steps:
- name: start-slack
  pull: if-not-exists
  image: plugins/slack
  settings:
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    recipient: mmich
    template: "*start* <${DRONE_BUILD_LINK}|building> *{{repo.name}}*.\n"
    username: drone
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    branch:
    - master
    - dev
    event:
    - push
    - tag

- name: get-tv-config
  pull: if-not-exists
  image: gcr.io/mirror-tv-275709/drone-cloud-sdk:latest
  commands:
      - gcloud source repos clone configs configs
      - cp configs/major-tom/gcskeyfile.json ./gcskeyfile.json
      - rm -rf configs
  environment:
    GOOGLE_CREDENTIALS:
      from_secret: google_credentials
  when:
    branch:
      - master
    event:
      - push
      - tag

- name: build-tv
  pull: if-not-exists
  image: node:major-tom
  commands:
    # - rm -f scripts/deploy_*.js
    # - cp scripts/deploy/deploy_tv.js script/deploy_tv.js
    - npm install
  when:
    branch:
    - master
    - dev
    event:
    - push

- name: publish-tv
  pull: if-not-exists
  image: plugins/gcr
  settings: 
    group: build
    repo: mirror-tv-275709/${DRONE_REPO_NAME}
    tag: dev-${DRONE_COMMIT_SHA:0:7}
  environment:
    GOOGLE_CREDENTIALS:
      from_secret: google_credentials

- name: deploy-tv
  pull: if-not-exists
  image: nytimes/drone-gke
  settings:
    cluster: tv-prod
    namespace: default
    template: manifests/major-tom/tv.yaml
    zone: asia-east1-c
  environment:
    TOKEN:
      from_secret: google_credentials

- name: finish-slack
  pull: if-not-exists
  image: plugins/slack
  settings:
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    recipient: mmich
    template: "{{#success build.status}}\n  Build<${DRONE_BUILD_LINK}|#{{build.number}}> *success* ${DRONE_REPO_NAME} was updated.\n{{else}}\n  Houston, we have a problem. Build <${DRONE_BUILD_LINK}|#{{build.number}}> failed. Fix me please.\n{{/success}}"
    username: drone
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    branch:
    - master
    - dev
    event:
    - push
    - tag
    status:
    - success
    - failure

image_pull_secrets:
  - gcr_docker_config
